package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.TextArea;

import javafx.scene.input.MouseEvent;

import javafx.scene.input.KeyEvent;

public class UIController {
	@FXML
	private Button btSend;
	@FXML
	private TextField textCommandInput;
	@FXML
	private TextArea textConsoleOutput;

	// Event Listener on Button[#btSend].onKeyPressed
	@FXML
	public void onKeyPressed(KeyEvent event) {
		// TODO Autogenerated
		System.out.println("onKeyPressed");
		String response = onCommandReceived(textCommandInput.getText());
		showToUser(response);
	}
	public void showToUser(String response) {
		textConsoleOutput.insertText(textConsoleOutput.getLength(), response);
		
	}
	// Event Listener on Button[#btSend].onMouseClicked
	@FXML
	public void onMouseClicked(MouseEvent event) {
		// TODO Autogenerated
		System.out.println("onMouseClicked");
		String response = onCommandReceived(textCommandInput.getText());
		showToUser(response);
	}
	
	private String onCommandReceived(String command){
		//Do whatever you want with the command here. Pass to LogicController to do its stuff.
		
		return LogicController.getInstance().onCommandProcess(command); //Stub
	}
}
